name: DataTables.Net Nuget Package Push

on:
  push:
    branches: [ v3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
            6.0.100
            5.0.403
            3.1.415
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Nuget pack
      run: dotnet pack src/DataTables.AspNet.Core/DataTables.AspNet.Core.csproj --output nuget-packages --configuration Debug
      
    - name: Nuget push
      env:
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push nuget-packages/*.nupkg --api-key %NUGET_KEY% --source "github"

