name: DataTables.Net Nuget Package Push

on:
  push:
    branches: [ v3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Nuget pack
      run: dotnet pack src/DataTables.AspNet.Core/DataTables.AspNet.Core.csproj --output nuget-packages --configuration Debug
    - name: Nuget push
      run: dotnet nuget push nuget-packages/*.nupkg --api-key %{{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
